# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaptura Projects
email: contacto@kapturaprojects.com
description: Kaptura Projects es una productora de audiovisuales en la CDMX.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://kapturaprojects.com" # the base hostname & protocol for your site
facebook: http://facebook.com
youtube:  http://youtube.com
instagram: http://instagram.com

# Build settings
markdown: kramdown

collections:
  - clients
  - proyects
  - members
